### ISSUE TITLE
Support all fixed-width Franca integer types on server side.

### ISSUE THREAD

**Issue by kbirken** [GENIVI/capicxx-wamp-tools#2]
Franca integer types: Int8, UInt8, Int16, UInt16, Int32, UInt32, Int64, UInt64.

Testcases for this feature: Interface with several methods, each testing these integer types as in- and out-argument of integer types. Also test with methods with multiple (and different) integer typed arguments.

**Comment by muehlbrandt** [comment]
Added test cases for fixed width integer types.
